name: commons-utils

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
    build:
      uses: sironAzevedo/ci-workflows/.github/workflows/java_build.yml@v0.0.12
      with:
        java-version: '17'
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

#    test:
#        runs-on: ubuntu-latest
#        needs: build
#        steps:
#          - uses: actions/checkout@v4
#          - name: Download updated pom.xml
#            uses: actions/download-artifact@v3
#            with:
#              name: updated-pom
#              path: ./
#          - name: Set up JDK 17
#            uses: actions/setup-java@v4
#            with:
#              distribution: 'temurin'
#              java-version: 17
#          - name: Cache Maven dependencies
#            uses: actions/cache@v3
#            with:
#              path: ~/.m2/repository
#              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#              restore-keys: |
#                ${{ runner.os }}-maven-
#          - name: Run unit tests
#            run: mvn test
#
#    create_pr:
#      needs: [build, test]
#      uses: sironAzevedo/ci-workflows/.github/workflows/git_pull_request.yml@v0.0.9