name: commons-utils

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
    build:
      uses: sironAzevedo/ci-workflows/.github/workflows/java_build.yml@v0.0.17
      with:
        java-version: '17'
        GITHUB_TOKEN: secrets.GH_TOKEN

    test:
      needs: [build]
      uses: sironAzevedo/ci-workflows/.github/workflows/java_build.yml@v0.0.17
      with:
        java-version: '17'
        GITHUB_TOKEN: secrets.GH_TOKEN


#    create_pr:
#      needs: [build, test]
#      uses: sironAzevedo/ci-workflows/.github/workflows/git_pull_request.yml@v0.0.9