name: commons-utils

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
    app:
      uses: sironAzevedo/ci-workflows/.github/workflows/feature.yml@v0.0.14
      with:
        java-version: '17'
        GITHUB_TOKEN: secrets.GH_TOKEN