name: commons-utils

on:
  push:
    branches: [ main ]

jobs:
    increment-version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Increment version
          id: increment_version
          run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            IFS='.' read -ra ADDR <<< "$VERSION"
            MAJOR=${ADDR[0]}
            MINOR=${ADDR[1]}
            PATCH=${ADDR[2]/-SNAPSHOT/}
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
            mvn versions:set -DnewVersion=$NEW_VERSION
            sed -i 's/<version>.*<\/version>/<version>'$NEW_VERSION'<\/version>/' pom.xml

    compile:
        runs-on: ubuntu-latest
        needs: increment-version
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Cache Maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - name: build & Compile project
          run: mvn clean compile install -DskipTests

    test:
        runs-on: ubuntu-latest
        name: Running tests
        needs: compile
        steps:
          - uses: actions/checkout@v4
          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: 17
          - name: Cache Maven dependencies
            uses: actions/cache@v3
            with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                ${{ runner.os }}-maven-
          - name: Run unit tests
            run: mvn test

    publish:
      runs-on: ubuntu-latest
      needs: test
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Configure Maven settings
          run: |
            mkdir -p ~/.m2
            echo "<settings><servers><server><id>github</id><username>\${env.GITHUB_ACTOR}</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          env:
            GITHUB_ACTOR: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        - name: Cache Maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - name: Publish package
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}